config/routes.rb
Rails.application.routes.draw do
  root to: "follows#index"

  devise_for :users

  resources :users, only: [:index, :show] do
    resources :quits, only: [:new, :create, :edit, :update], shallow: true
  end

  resources :follows, only: [:create, :destroy]
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    if user.admin?
      can :manage, :all
    else
      can :read, :all
    end
    alias_action :create, :update, :destroy, to: :crud
    can :crud, Quit, user_id: user.id
  end
end

app/models/follow.rb
# == Schema Information
#
# Table name: follows
#
#  id          :integer          not null, primary key
#  follower_id :integer
#  followed_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Follow < ActiveRecord::Base
  # Follower is a User whose id is the column follower_id
  belongs_to :follower, class_name: :User, foreign_key: :follower_id
  # Followed is a User whose id is the column followed_id
  belongs_to :followed, class_name: :User, foreign_key: :followed_id
end

app/models/quit.rb
# == Schema Information
#
# Table name: quits
#
#  id         :integer          not null, primary key
#  text       :text
#  created_at :datetime
#  updated_at :datetime
#  user_id    :integer
#

class Quit < ActiveRecord::Base
  belongs_to :user

  validates :text, presence: true
  validates :user_id, presence: true
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :integer          not null, primary key
#  name                   :string(255)
#  created_at             :datetime
#  updated_at             :datetime
#  email                  :string(255)      default(""), not null
#  encrypted_password     :string(255)      default(""), not null
#  reset_password_token   :string(255)
#  reset_password_sent_at :datetime
#  remember_created_at    :datetime
#  role                   :integer          default(0)
#

class User < ActiveRecord::Base
  enum role: [ :user, :admin, :moderator ] # Converts role to string for helpers.

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :quits
  # The id of the user matches the follower_id column on the follows table
  has_many :follows, foreign_key: :follower_id
  # The users that are returned by having the method followed mapped onto the follows.
  has_many :followed_users, through: :follows, source: :followed
  # The quits that are posted by the the people this user follows
  has_many :followed_users_quits, through: :followed_users, source: :quits

  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) << :name
  end
end

app/controllers/follows_controller.rb
class FollowsController < ApplicationController

  def index
    if current_user
      @follows = current_user.followed_users_quits
    else
      redirect_to users_path
    end
  end

  def create
     followed = User.find(params[:user_id])
     follower = current_user
     Follow.create(followed: followed, follower: follower)
     redirect_to user_path(followed)
  end

  def destroy
     follow = Follow.find(params[:id])
     follow.delete
     redirect_to user_path(follow.followed)
  end
end

app/controllers/quits_controller.rb
class QuitsController < ApplicationController
  load_and_authorize_resource

  def new
    @user = User.find params[:user_id]
    @quit = @user.quits.build
  end

  def create
    @user = User.find params[:user_id]
    @quit = @user.quits.build quit_params
    if @quit.save
      redirect_to @quit.user
    else
      render "new"
    end
  end

  def edit
    @quit = Quit.find params[:id]
  end

  def update
    @quit = Quit.find params[:id]
    if @quit.update quit_params
      redirect_to @quit.user
    else
      render "edit"
    end
  end

  private

  def quit_params
    params.require(:quit).permit(:text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find params[:id]
    @follow = Follow.where(followed: @user, follower: current_user).first
  end

  def index
    @users = User.all
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/follows/index.html.slim
h1 Quits you follow

- @follows.each do |follow|
  h4 = "#{follow.text} from #{follow.user.name}"

app/views/layouts/application.html.slim
doctype html
html
  head
    title Lecture 10
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  body
    .container
      .header
        ul.nav.nav-pills.pull-right
          li = link_to "Home", root_path
          - if user_signed_in?
            li = link_to current_user.name, user_path(current_user)
            li = link_to "Logout", destroy_user_session_path, method: :delete
          - else
            li = link_to "Sign In", new_user_session_path
            li = link_to "Sign Up", new_user_registration_path
        h3.text-muted Quitter
      = yield

app/views/quits/edit.html.slim
h1 Editing Quit

= simple_form_for @quit do |f|
  = f.input :text
  = f.button :submit

app/views/quits/new.html.slim
h1 Creating Quit for #{@user.name}

= simple_form_for [@user, @quit] do |f|
  = f.input :text
  = f.button :submit

app/views/users/index.html.slim
h1 Users

- @users.each do |user|
  h2 = link_to user.name, user
  h4 Has #{pluralize user.quits.count, "quit"}

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/users/show.html.slim
h1 #{@user.name} #{link_to "+", new_user_quit_path(@user)}
- if @follow
  h4 = link_to "Unfollow", follow_path(@follow), method: :delete
- elsif current_user != @user
  h4 = link_to "Follow", follows_path(user_id: @user.id), method: :post


h3 Quits

- @user.quits.each do |quit|
  - if can? :update, quit
    h4 = link_to quit.text, edit_quit_path(quit)
  - else
    h4 = quit.text

h3
  | Who I follow
  - @user.followed_users.each do |user|
    h4 = link_to user.name, user_path(user)